### ISSUE TITLE
Experiment with thermal gap pads for battery temp sensors.

### ISSUE THREAD

**Issue by squarewavesbelow** [librespacefoundation/upsat-eps-hardware#10]
The two battery temperature sensors do not have a physical contact with the batteries, which might lead to a failure in the battery temperature protection system. Experiment with thermal gap pad to establish a direct thermal path from battery cell to temp sensor to avoid ny surprises in vacuum chamber.

**Comment by ppapadeas** [comment]
closing in favor of thermal epoxy
